_wandb:
    value:
        cli_version: 0.25.1
        code_path: code/examples/baselines/ppo/ppo_fast.py
        e:
            uadi2tw6wz60y1x8m9jn7l4l6ofyb4zb:
                args:
                    - --env_id
                    - StackCube-v1
                    - --reach_variant
                    - tanh
                    - --reach_k
                    - "2.0"
                    - --num_envs
                    - "256"
                    - --total_timesteps
                    - "40000000"
                    - --track
                    - --wandb_entity
                    - agv_rego
                    - --wandb_project_name
                    - REP
                    - --wandb_group
                    - REP
                    - --seed
                    - "123"
                codePath: examples/baselines/ppo/ppo_fast.py
                codePathLocal: examples/baselines/ppo/ppo_fast.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "499430440960"
                        used: "430789758976"
                email: theyanesher@kgpian.iitkgp.ac.in
                executable: /home/theya/REP/REP/rep/bin/python
                git:
                    commit: e4bd8e93c5f500359e3a5d6be495e6ee2cd88757
                    remote: https://github.com/ApRL-IITKGP/REP.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-85843b45-d32a-8c68-ccec-299f62a8fa80
                host: theya-Dell-G15-5530
                memory:
                    total: "16436490240"
                os: Linux-6.8.0-101-generic-x86_64-with-glibc2.35
                program: /home/theya/REP/REP/examples/baselines/ppo/ppo_fast.py
                python: CPython 3.10.12
                root: /home/theya/REP/REP
                startedAt: "2026-03-13T22:43:42.174178Z"
                writerId: uadi2tw6wz60y1x8m9jn7l4l6ofyb4zb
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 49
                - 105
            "2":
                - 1
                - 49
                - 105
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.12
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
anneal_lr:
    value: false
batch_size:
    value: 12800
capture_video:
    value: true
checkpoint:
    value: null
clip_coef:
    value: 0.2
clip_vloss:
    value: false
compile:
    value: false
control_mode:
    value: pd_joint_delta_pos
cuda:
    value: true
cudagraphs:
    value: false
ent_coef:
    value: 0
env_cfg:
    value:
        control_mode: pd_joint_delta_pos
        env_horizon: 50
        env_id: StackCube-v1
        gate_variant: hard
        num_envs: 256
        obs_mode: state
        partial_reset: true
        reach_alpha: 10
        reach_k: 2
        reach_k_max: 20
        reach_k_min: 2
        reach_variant: tanh
        render_mode: rgb_array
        reward_mode: normalized_dense
        sim_backend: gpu
        terminal_variant: hard_jump
env_id:
    value: StackCube-v1
env_vectorization:
    value: gpu
eval_env_cfg:
    value:
        control_mode: pd_joint_delta_pos
        env_horizon: 50
        env_id: StackCube-v1
        gate_variant: hard
        num_envs: 16
        obs_mode: state
        partial_reset: false
        reach_alpha: 10
        reach_k: 2
        reach_k_max: 20
        reach_k_min: 2
        reach_variant: tanh
        render_mode: rgb_array
        reward_mode: normalized_dense
        sim_backend: gpu
        terminal_variant: hard_jump
eval_freq:
    value: 25
eval_partial_reset:
    value: false
eval_reconfiguration_freq:
    value: 1
evaluate:
    value: false
exp_name:
    value: ppo_fast
finite_horizon_gae:
    value: true
gae_lambda:
    value: 0.9
gamma:
    value: 0.8
gate_variant:
    value: hard
learning_rate:
    value: 0.0003
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 400
norm_adv:
    value: true
num_envs:
    value: 256
num_eval_envs:
    value: 16
num_eval_steps:
    value: 50
num_iterations:
    value: 3125
num_minibatches:
    value: 32
num_steps:
    value: 50
partial_reset:
    value: true
reach_alpha:
    value: 10
reach_k:
    value: 2
reach_k_max:
    value: 20
reach_k_min:
    value: 2
reach_variant:
    value: tanh
reconfiguration_freq:
    value: null
reward_scale:
    value: 1
save_model:
    value: false
save_train_video_freq:
    value: null
save_trajectory:
    value: false
seed:
    value: 123
target_kl:
    value: 0.1
terminal_variant:
    value: hard_jump
torch_deterministic:
    value: true
total_timesteps:
    value: 40000000
track:
    value: true
update_epochs:
    value: 4
vf_coef:
    value: 0.5
wandb_entity:
    value: agv_rego
wandb_group:
    value: REP
wandb_project_name:
    value: REP
